### ISSUE TITLE
compatibility with sprockets 4

### ISSUE THREAD

**Issue by mischa-s** [ackama/rails-template#10]
A new version of sprockets was recently released which creates the following error

![image](https://user-images.githubusercontent.com/22373872/66723568-0261e600-ee77-11e9-8ef7-479782c330bf.png)

The short term fix is to add  `gem "sprockets", "~> 3.0"` to the gem file but a proper fix will need to be implement https://github.com/rails/sprockets/blob/master/UPGRADING.md#guide-to-upgrading-from-sprockets-3x-to-4x

**Comment by joshmcarthur** [comment]
@mischa-s this doesn't help you in the short term, but I believe sprockets may not be a thing that is required at all if you're happy to stick with the `*_pack_tag` helpers, since Webpacker takes care of all this without involving sprockets.

**Comment by mischa-s** [comment]
thanks I'll have a look at that

**Comment by mischa-s** [comment]
Also going to leave this here. If it gets merged it will add the option of specifying a custom route for the manifest https://github.com/rails/sprockets-rails/pull/446

**Comment by eoinkelly** [comment]
Rails 6.0.1 brings in `sprockets-rails (>= 2.0.0)` as a dependency so we can't really avoid installing it, even if you plan to use webpacker only in the app.

**Comment by eoinkelly** [comment]
Fixed by PR #13
