### ISSUE TITLE
Bug fixes to the sidekiq variant

### ISSUE THREAD

**Issue by eoinkelly** [ackama/rails-template#113]
* `redis` gem not required (`sidekiq` gem pulls it in already)
* we shouldn't install sidekiq as the global active_job.queue_adaptor because it forces you to have redis running to run your tests
* we seem to be setting up the routes for the web panel in both an initializer and routes.rb - we should only do this once

**Comment by joshmcarthur** [comment]
> we shouldn't install sidekiq as the global active_job.queue_adaptor because it forces you to have redis running to run your tests

I don't think is true. In `config/environments/test.rb` the test adapter is normally set to `:inline` or `:async`

**Comment by Rabid-Dan** [comment]
Resolved by #134
