### ISSUE TITLE
Add capistrano variant

### ISSUE THREAD

**Issue by eoinkelly** [ackama/rails-template#114]
We use cap enough that adding a variant seems useful

**Comment by eoinkelly** [comment]
Given that most of our Capistrano deployments go to AWS I think this feature should include code to introspect an AWS environment and get the dynamic IPs of the app servers.

**Comment by fractalcactus** [comment]
is there an Ackama project that is a good example of how we use Capistrano? perhaps [NZX](https://github.com/ackama/nzx-mas)?

**Comment by joshmcarthur** [comment]
@fractalcactus messaged you with a list of candidate projects - I'm not sure I want to list them in the public repo :-)

**Comment by fractalcactus** [comment]
I've gone as far as I can on [this feature](https://github.com/ackama/rails-template/tree/Feature/114-add-capistrano-aws-variant), but need some help to finish it off

**Comment by eoinkelly** [comment]
@fractalcactus Have messaged you on Slack.
