### ISSUE TITLE
Bundler.with_clean_env is deprecated and will be removed in Bundler 3

### ISSUE THREAD

**Issue by eoinkelly** [ackama/rails-template#116]
[Deprecation details](https://github.com/rubygems/bundler/blob/d4993be66fa2e76b3ca00ea56a51ecab5478b726/UPGRADING.md#bundler-3)

We used `Bundler.with_clean_env` in a few places. We should replace these with the appropriate new API (as documented in the link above)

**Comment by joshmcarthur** [comment]
#125
