### ISSUE TITLE
Content security policy always tries to report CSP violations, even when unconfigured

### ISSUE THREAD

**Issue by joshmcarthur** [ackama/rails-template#124]
What I did:

* Created a new Rails 6 application
* Caused a CSP violation (in this case, using a [version of Trix that does not support the csp-nonce meta tag](https://github.com/basecamp/trix/pull/698). 

What I expected:

* The error to be raised in my devtools

What happened:

* The error was raised in my devtools
* Chrome reported a failed network request to `https://somecode.ingest.sentry.io/api/SOMENUMS/security/?sentry_key=SOMETHING`

Screenshots:

![image](https://user-images.githubusercontent.com/292020/89139378-903bc880-d592-11ea-9319-26ab5aff930a.png)

---

This is because CSP is configured with a report-uri using `ENV.fetch`, so the application won't start without a report URI set. A side effect of this is that the example SENTRY_CSP_HEADER_REPORT_ENDPOINT in .env is uncommented, causing this behaviour to be enabled.

I suspect that the most sensible (and least noisy) configuration would be to set `report_only` to true in `Rails.env.development || Rails.env.test?`, so that CSP violations won't be sent in these environments.

**Comment by eoinkelly** [comment]
Definitely a bug but I'm wondering if we make CSP "report only"  in dev and test whether devs will just not see the problems until they fail to work in staging. If you don't have the JS console visible then those errors are invisible locally.

Maybe the right fix is to:

```
  policy.report_uri ENV["SENTRY_CSP_HEADER_REPORT_ENDPOINT"]
```

so that the reporting URI isn't required for app boot?
