### ISSUE TITLE
Break the fork relationship between this repo and joshmcarthur/rails-template

### ISSUE THREAD

**Issue by eoinkelly** [ackama/rails-template#128]
This was discussed somewhat on #34 . The consensus seems to be that we have made sufficient changes to this repo that pulling in any changes from upstream isn't feasible anymore.

I believe we have to contact Github support to make this happen.

When this happens, we should ensure that the README of this repo gives credit to @joshmcarthur and https://github.com/mattbrictson/rails-template upon whose work we are built.

**Comment by joshmcarthur** [comment]
:wave: :broken_heart:

**Comment by joshmcarthur** [comment]
I also wouldn't mind seeing if we can track down a contact email for Matt and send him a bit a note saying thanks. We would 100% not be where we are now without the foundational work they did.

**Comment by Rabid-Dan** [comment]
@joshmcarthur sending an email to Matt sounds like a neat idea. His github account has a link to his site which it looks like hes got an email contact at https://mattbrictson.com/

**Comment by fractalcactus** [comment]
we can contact Github support, or alternatively use the 'import repository' feature. Here is a copy of ` ackama /
rails-template`. 
 https://github.com/ackama/ackama-rails-template
The issues and PRs aren't pulled over automatically, but here's a tool I can use to at least import the issues:
https://github.com/IQAndreas/github-issues-import
Does this sound like an appropriate solution? (As well as adding credit to @joshmcarthur and https://github.com/mattbrictson/rails-template)

**Comment by joshmcarthur** [comment]
@fractalcactus I think in this instance it might be better to just contact Github support. It sounds like they can just flip a flag to set it to normal model.

**Comment by joshmcarthur** [comment]
If we were a larger project I'd carry across all the issues and stuff, but I don't think at this early stage we want to rewrite all that stuff.

**Comment by fractalcactus** [comment]
request sent to github support

**Comment by fractalcactus** [comment]
Github support has removed the parent fork relationship, and I've made a [PR](https://github.com/ackama/rails-template/pull/153) to add credit to the README
