### ISSUE TITLE
Move Sidekiq to an external variant 

### ISSUE THREAD

**Issue by joshmcarthur** [ackama/rails-template#143]
As a template maintainer

I want to have an established and documented path to split a variant out into its own repository

So that I can reduce the complexity of the core template 

---

- [ ] Move Sidekiq into this new structure
- [ ] Update the rails template to load the Sidekiq variant from an external repo
- [ ] Support vartiant loading from local path, repo URL, or absolute URL
- [ ] Establish CI process in external variant
- [ ] Create a new repository template structure repo (suggest: rails-template-pdf-rendering)

**Comment by eoinkelly** [comment]
I'm inclined to close this because I don't think the outcome would be worth the effort. I think we setup Sidekiq on _most_ of our apps so it being in the default template doesn't feel icky to me. @joshmcarthur please re-open if you disagree.
