### ISSUE TITLE
Support loading template configuration from a YAML file

### ISSUE THREAD

**Issue by joshmcarthur** [ackama/rails-template#144]
As a template generator

I want to be able to use a YAML file to configure the Rails template run without being asked for inputs

So that I can headlessly generate templates, or quickly generate an application with predefined settings and variants.

---

- [ ] Extend method in core template that asks for settings to check a YAML file before prompting the user
- [ ] Load the YAML file from multiple locations:
  - From a location provided by the user (I _think_ this needs to be an environment variable, I don't think we can add our own flags to `rails new`
  - From `rails-template.yml` in the working directory if it exists, or
  - From `.rails-template.yml` in the user's home directory (also check if there are 'best practice' locations for this like $XDG_CONFIG_HOME that will work multiplatform)
- [ ] Switch over CI to use YAML files for build matrices, rather than shoving strings into the rails new command
- [ ] Provide some examples of YAML files in the `examples` directory

**Comment by eoinkelly** [comment]
Given that the Rails convention is `_`, should it be `rails_template.yml` as the default name? I know this is bikesheddy but :shrug: this is the place for that :smile:

**Comment by eoinkelly** [comment]
This has been completed. Config is now in `ackama_rails_template.config.yml` (file path can be controlled by ENV var)
