### ISSUE TITLE
Use Lighthouse CI for performance and accessibility testing

### ISSUE THREAD

**Issue by Rabid-Dan** [ackama/rails-template#145]
As a developer using this template

I want to use the official Lighthouse CI tools 

So that I have a more time effective way to run audits

-----------------------------------------------------------

Using the official CI tools https://github.com/GoogleChrome/lighthouse-ci could help to speed up our test suites and reduce the need for developers to write individual tests.

**Comment by Rabid-Dan** [comment]
This requires further investigation so I'm currently doing some trials to see how viable it would be across our various repo locations and setups before any feature work is done for the ticket.

**Comment by Rabid-Dan** [comment]
I've had a play around with this today but the major blocker to us using it seems to be that you cant stop it from running every audit. You _can_ tell it to not include a category in the assertions but that only appears to stop it from failing/erroring on failing assertions for that category, it doesn't actually stop the tool from running them.
This means that it actually ends up running more slowly than just using lighthouse-matchers and requires a bunch of extra config. 
It's possible that I'm missing something in the setup here and that theres an option to do this that I just cant see but it might need a second pass from someone else.

**Comment by joshmcarthur** [comment]
The other aspect here that we need to be cautious of is that it does require the application to be available. This means that we need to either run lighthouse-ci as part of our RSpec run (and collect and parse the results, which is effectively what RSpec is doing, or have a CI process that actually starts a test server, loads in the database, runs lighthouse-ci, then cleans up.

**Comment by joshmcarthur** [comment]
@Rabid-Dan it looks like https://github.com/GoogleChrome/lighthouse-ci/blob/master/docs/configuration.md#settings defines the ability to pass options to Lighthouse, which would allow categories or particular audits to be skipped.

**Comment by joshmcarthur** [comment]
e.g. https://github.com/GoogleChrome/lighthouse-ci/blob/master/docs/configuration.md#settings

**Comment by Rabid-Dan** [comment]
oh neat! Thanks @joshmcarthur I was looking for the "onlyCategories" options in the ci docs but I couldnt find them. I'll take another crack at it with that to see if it makes a difference

**Comment by Rabid-Dan** [comment]
I had another play with trying to get this to perform a bit better and with the current test configuration its only marginally slower per page than lighthouse matchers https://github.com/Rabid-Dan/lighthouse-ci-test/tree/test. 
Something thats not added to that yet is precompiling assets which helped out a bit.
One interesting thing is that while its slightly slower for a single audit type compared to our current solution, it ends up being a bit quicker for multiple audits  (e.g accessibility _and_ performance rather than one or the other). So there some potential gains there.
Probably requires a bit of extra investigation or a second crack at it but I'm resourced to other things now so I'll have to leave my trial at this point for now.

**Comment by eoinkelly** [comment]
This has been shipped
