### ISSUE TITLE
Should we create a rubocop config for this template repo (not for the generated apps)

### ISSUE THREAD

**Issue by eoinkelly** [ackama/rails-template#146]
It confuses new devs to this project that rubocop doesn't pass on this repo. We would probably need a custom `.rubocop.yml` because quite a bit of the "railsy" one we normally use doesn't apply e.g. any of the `Rails/` or `Performance/` cops.

**Comment by fractalcactus** [comment]
I"m keen for a custom `.rubocop.yml`, and in the meantime, a note in the readme that `rubocop` can't be run on the template itself yet
