### ISSUE TITLE
More granular commits

### ISSUE THREAD

**Issue by joshmcarthur** [ackama/rails-template#149]
At the moment, the template does one gigantic commit when it finishes. I would prefer to have smaller commits as each 'bit' was applied, so it's easier to see which part of the generator did what.

This is going to be particularly important to support external variants, since I think those should add a commit each time they are run.

**Comment by fractalcactus** [comment]
Hi there @joshmcarthur, I'm not sure what you meant by "the template does one gigantic commit when it finishes".
`rails new blog` + `cd blog` + `git log` fails with `fatal: your current branch 'master' does not have any commits yet`. What am I missing here? Thanks!

**Comment by joshmcarthur** [comment]
Just to clarify, is that being run with the template, or not?

[There's a line in the template that adds a git commit right at the end of the run](https://github.com/ackama/rails-template/blob/main/template.rb#L76). I was hoping we could explore the practicality of performing several WIP commits as the template runs, so there are discrete checkpoints we can reset to (or just view the changes of) if necessary.

At the moment, I think the most sensible checkpoints we have are the variants. Because there's one big commit, at the moment it's hard to see what files have been modified by what variant. If we were able to add commits as we go, I would hope we would be able to examine each commit to see what was changed.

As an example, running `rails new` with the template could generate a git history like:

```
abc123 Initial commit: Project generated with options --database=postgresql --skip-test-unit
abc124 Variant: Add Sidekiq for background processing (adds Redis dependency)
abc125 Variant: Add Foundation for frontend development
abc126: Variant: Add devise for user authentication
```
Of course, the actual commit messages would be something we would have to decide on to achieve a balance between brevity and explaining the underlying change introduced by the variant and why it is added. We could eventually add a commit description as well as a title to explain in more detail why we use Sidekiq (for example), compared to alternatives.

With the commit list above, if I wanted to see what the Sidekiq variant actually did, I can run `git show abc124`. I can't do that at the moment, since all the changes introduced by the template, including all the variants I have opted in to running.

**Comment by fractalcactus** [comment]
<img width="615" alt="image" src="https://user-images.githubusercontent.com/8527715/90571192-68409c00-e205-11ea-8e74-1c6e1a4b1551.png">
Thanks @joshmcarthur , that all makes sense, except I'm not seeing the giant git commit in either the template, or the newly generated project.

**Comment by joshmcarthur** [comment]
Weird! It definitely gets generated, you can see it in the latest CI run: https://github.com/ackama/rails-template/runs/983357847?check_suite_focus=true#step:7:1926

What command are you running to gen that project, so I can try and replicate?

**Comment by fractalcactus** [comment]
very strange indeed!
`rails new blog` + `cd blog` + `git log`
I've tried this a few times

**Comment by fractalcactus** [comment]
............................................________
....................................,.-'"...................``~.,
.............................,.-"..................................."-.,
.........................,/...............................................":,
.....................,?......................................................,
.................../...........................................................,}
................./......................................................,:`^`..}
.............../...................................................,:"........./
..............?.....__.........................................:`.........../
............./__.(....."~-,_..............................,:`........../
.........../(_...."~,_........"~,_....................,:`........_/
..........{.._$;_......"=,_......."-,_.......,.-~-,},.~";/....}
...........((.....*~_......."=-._......";,,./`..../"............../
...,,,___.`~,......"~.,....................`.....}............../
............(....`=-,,.......`........................(......;_,,-"
............/.`~,......`-...................................../
.............`~.*-,.....................................|,./.....,__
,,_..........}.>-._...................................|..............`=~-,
.....`=~-,__......`,.................................
...................`=~-,,.,...............................
................................`:,,...........................`..............__
.....................................`=-,...................,%`>--==``
........................................_..........._,-%.......`
..................................., 

I didn't generate a new app with the template flag!

**Comment by fractalcactus** [comment]
I will continue with this issue when https://github.com/ackama/rails-template/pull/157 is approved, so I'm sure that I understand the variants

**Comment by eoinkelly** [comment]
We don't think we'll get to this one anytime soon
