### ISSUE TITLE
should all  variants be applied "after setup and initial install, but before commit"?

### ISSUE THREAD

**Issue by fractalcactus** [ackama/rails-template#151]
the [frontend-base variant](https://github.com/ackama/rails-template/blob/8bb6271408a58c75c80406504cc012cabda486fc/template.rb#L54) is applied before the [comment](https://github.com/ackama/rails-template/blob/8bb6271408a58c75c80406504cc012cabda486fc/template.rb#L58) ` # Apply variants after setup and initial install, but before commit`, should it go after the comment along with the other `apply variant` calls?

**Comment by eoinkelly** [comment]
Discussed, we think current behaviour is ok
