### ISSUE TITLE
Add doc outlining the base technology incorporated into an app generated from this template and available variants.

### ISSUE THREAD

**Issue by Rabid-Dan** [ackama/rails-template#152]
A new rails app generated using this template includes quite a number of files for various tooling and technology choices such as rubocop, prettier, eslint, docker, stylelint, simplecov, overcommit etc. This is incredibly useful and saves a lot of time when starting a new project, as well as keeping our base tech choices consistent across projects.

At this point though I wonder if the length of that list is beginning to impede the approachability of new code bases, particularly for more junior devs. Even as a senior the number of config files is initially a bit overwhelming with minimal additional context as to what they do or why they're there.

A filled out readme section or technical choices doc for this repo would help this by acting as a summary/first port of call for those looking for more information. I wouldn't expect it to necessarily explain how each thing works but instead to include each tech choice, the config files relevant to it,  a one liner on what it does at a high level, a link to its base docs/site, and maybe any significant deviations from its default setup (eg eslint uses the eslint-config-ackama plugin for its rules and setup).

Similarly as the number of variants grows, so too does the list of default tech included by each of them. A summary section in the readme of each variant and what it includes/does would be helpful in understanding what developers are getting by default without having to dig through the templating code.

**Comment by joshmcarthur** [comment]
@Rabid-Dan this might dovetail nicely with #149, what do you reckon?

**Comment by fractalcactus** [comment]
I would be really keen to take on this issue, as I need to learn about the various tools and technology in the template. I could bundle #149 in with this issue.

**Comment by Rabid-Dan** [comment]
@joshmcarthur yeah absolutely,  #149 would provide an additional set of "documentation" through the commit history and the process of breaking it down into individual commits feels like it would help avoid anything getting missed in this.

**Comment by fractalcactus** [comment]
I would repeat [this format](https://github.com/ackama/rails-template/pull/154/files) for each custom tool and configuration, going through this list of [Ackama technology preferences](https://github.com/ackama/wiki/wiki/Ackama-Technology-Preferences), and other significant deviations that Dan mentioned e.g the eslint-config-ackama plugin. How does that look to everyone?

**Comment by Rabid-Dan** [comment]
@fractalcactus That format looks good to me, I think rather than going through that whole list of Ackama tech preferences it'd be good to just document the ones we've got built into apps generated by this template. My thoughts with this issue were that we could have two sections, one for general tooling tech (like eslint, rubocop etc) and the tech preferences that you get by default, and a second "variants" section for explaining what each variant is, if its optional or not, and what it does.

**Comment by fractalcactus** [comment]
those two sections sound like a great idea @Rabid-Dan
