### ISSUE TITLE
rm rubocop.yml?

### ISSUE THREAD

**Issue by fractalcactus** [ackama/rails-template#155]
`rubocop.yml` doesn't seem necessary since `rubocop.yml.tt` exists, and includes the one line that `rubocop.yml` contains. Can we remove `rubocop.yml`?

**Comment by eoinkelly** [comment]
Unless I'm forgetting something, I don't think we should remove it.

`rubocop.yml` is/should be the rubocop config for this repo. `rubocop.yml.tt` is the template that creates the rubocop config for the generated Rails apps. 

I'm honestly not sure if this repo passes the rubocop config in `rubocop.yml` - currently it just imports our default config but that's quite tuned for Rails apps and this app is a bit different.

**Comment by fractalcactus** [comment]
oh, I understand! thanks @eoinkelly
