### ISSUE TITLE
Idea: Script for dumping the database

### ISSUE THREAD

**Issue by eoinkelly** [ackama/rails-template#160]
We sometimes find ourselves needing to download a dump of a database for support reasons e.g. to diagnose a bug that only appears in a deployed environment.

Briefly discussed with @joshmcarthur and we think the following could work:

* Create a rake task that pulls in the DB credentials that Rails uses, then shells out to `pg_dump` to dump the database into some tmp directory. If we want/need to anonymize the data then this could be done here too.
* Setup capistrano to call that rake task and download the file.

Then you could do something like the following on a dev machine (assuming you have the required permissions):

```
# saves file to ./tmp/YYYY-MM-DD-RAILS_ENV-database.pg_dump
$ bundle exec cap staging db:dump
```

**Comment by eoinkelly** [comment]
It would be interesting to bake in some anonymisation into this. _Most_ of our apps have a `users` table with predictable column names (from `devise`) so it seems achievable. I'm not sure `pg_dump` works in that scenario. More investigation required.

**Comment by fractalcactus** [comment]
blocked until completion of [Add capistrano variant](https://github.com/ackama/rails-template/issues/114)

**Comment by fractalcactus** [comment]
would also be useful to [add a cap task to check for permissions and repository access](https://capistranorb.com/documentation/getting-started/cold-start/#2-writing-our-first-cap-task-to-formalize-this-into-a-check)

**Comment by eoinkelly** [comment]
We have decided that this idea should live outside this template.
