### ISSUE TITLE
Add .DS_Store to .gitignore

### ISSUE THREAD

**Issue by lamorrison** [ackama/rails-template#163]
We don't want to accidentally commit that pesky MacOS system file. It's theoretically a security issue.

This issue was made in response to the BLP pen test results. We'd like to pass pen test criteria by default.

**Comment by G-Rath** [comment]
Might as well add some other sensible ones while we're at it:

```
.idea/
.vscode/
.terraform/
node_modules/

.eslintcache
pids
*.pid
*.swp
*.seed
*.pid.lock
*.tsbuildinfo
```

(I'm pretty sure some of these are already added, but I know at least the first three aren't)
