### ISSUE TITLE
Consider enforcing HTTPS in CSP

### ISSUE THREAD

**Issue by lamorrison** [ackama/rails-template#164]
The content security policy doesn't enforce HTTPS by default. This isn't _necessarily_ appropriate and could be confusing for sites which do use non-HTTPS partners. On the other hand it's 2020 already :man-shrugging:

This issue is here because it seems work discussing but I'm likely to forget.

**Comment by eoinkelly** [comment]
That is true about the default for Rails itself but this template currently customises it quite a bit - see https://gist.github.com/eoinkelly/077bb7b3c3f7735423a1579b80143557

Our default policy is **very** strict (basically everything is either `:none` or `:self`). We don't really talk about HTTP vs HTTPS in the policy but all our examples (outside of things only in Rails development env) show HTTPS so I'm not seeing what change we should make. 

@lamorrison Did you have something specific in mind or was this a more general _Don't forget about CSP_ issue?
