### ISSUE TITLE
Error on install

### ISSUE THREAD

**Issue by krlosgilson** [ackama/rails-template#165]
When trying to install, the following message appears: "Could not find gem 'pg (> = 0.18)' in any of the gem sources listed in your Gemfile."

**Comment by joshmcarthur** [comment]
Hi @krlosgilson! 

It'd be really useful if we could have a bit more information here. Can you provide the command you were using to generate a new rails application using this template when you ran into this error, and the output of the template generation?

Also, does the command `gem install pg -v "~> 0.18"` work for you?

**Comment by eoinkelly** [comment]
@krlosgilson Closing for now. Feel free to create new issue if you are still having issues with this.
