### ISSUE TITLE
Run yarn audit in CI

### ISSUE THREAD

**Issue by eoinkelly** [ackama/rails-template#168]
AFAICT we don't run `yarn audit` as part of our CI run. We should fix that. See the generated `bin/ci-run` script for details.

**Comment by G-Rath** [comment]
I built [`audit-app`](https://github.com/G-Rath/audit-app) for us to use to allow teams to ignore vulnerabilities, which is a drop-in replacement.

**Comment by eoinkelly** [comment]
@G-Rath I think we should discuss `audit-app` in a separate issue. I think the current behaviour is a bug so I'd like to scope this issue to that.
