### ISSUE TITLE
Rename 'staging' environment to 'uat'

### ISSUE THREAD

**Issue by joshmcarthur** [ackama/rails-template#17]
We generally use 'UAT' as our 'staging'-equivalent environment name, so we should rename mentions of this environment.

**Comment by eoinkelly** [comment]
I'm not sure that's true more often than it is not. I think we typically either have staging +production or staging+uat+production (if the client wants a separate UAT env). Just my gut feeling on this, happy to discuss.

**Comment by joshmcarthur** [comment]
I know that for all recent projects, I've gone for UAT+Production to more accurately reflect the purpose of the environments. I tend to introduce staging when clients are requesting an environment to use that is pre-production but with safe data.

**Comment by eoinkelly** [comment]
So the flow of code changes would be `UAT -> Staging -> Production`?

**Comment by joshmcarthur** [comment]
Yes, but staging is often not there for smaller clients.

**Comment by eoinkelly** [comment]
I'm not against this but IIRC we decided that the flow should be `Staging -> UAT -> Production` when we last discussed branch naming - https://github.com/ackama/wiki/wiki/Branch-naming-conventions-and-deployment-process

**Comment by joshmcarthur** [comment]
That feels the wrong way around to me though. Surely UAT should be the next immediate step after dev completes, and signed-off features make their way to staging for pre-prod usage? 

It sounds like we need to close this issue while we decide on our deployment flow, and re-open if we can settle on a suggested flow. 

FWIW I think that I got this deployment flow mixed up because I _thought_ it should be that way. Now we've done a bunch of projects deploying with that flow, we should figure out how to bring things back into alignment and what to do in the future.

**Comment by eoinkelly** [comment]
@joshmcarthur Are there any actions to take on this before we close it?

**Comment by eoinkelly** [comment]
Closing because if we want to change this flow, we'll need a lot more internal comms between teams.
