### ISSUE TITLE
Add http basic auth

### ISSUE THREAD

**Issue by JamesYang76** [ackama/rails-template#175]
We use http basic auth on almost all rails apps - I think it would be great to have it as a part of this template
```ruby
 before_action :http_basic_auth

  def http_basic_auth
    return unless ENV["HTTP_BASIC_AUTH_USERNAME"] && ENV["HTTP_BASIC_AUTH_PASSWORD"]

    authenticate_or_request_with_http_basic("Username and Password please") do |username, password|
      username == ENV["HTTP_BASIC_AUTH_USERNAME"] && password == ENV["HTTP_BASIC_AUTH_PASSWORD"]
    end
  end
```

**Comment by eoinkelly** [comment]
@JamesYang76 You'll be happy to hear we already do! :smile: - check out https://github.com/ackama/rails-template/blob/main/app/middleware/http_basic_auth.rb

**Comment by JamesYang76** [comment]
@eoinkelly Good. I am going to close this issue
