### ISSUE TITLE
Consider using hiredis for sidekiq variant

### ISSUE THREAD

**Issue by eoinkelly** [ackama/rails-template#179]
[hiredis-rb](https://github.com/redis/hiredis-rb) is a Ruby wrapper around [hiredis](https://github.com/redis/hiredis) which is a higher performance redis driver than the pure ruby driver that comes with [redis-rb]

### Reasons to consider the change

* https://github.com/redis/hiredis-rb#benchmarks

### Reasons not to consider the change

* hiredis is a C dependency so are there portability issues?
* Is redis driver performance actually any kind of bottleneck for sidekiq?

### Example of the change

The change would require the following:

```ruby
# Gemfile

# hiredis must be **before** redis in Gemfile
gem "hiredis"
gem "redis", require: ["redis", "redis/connection/hiredis"]
gem "sidekiq"
```

**Comment by p1p1tt0** [comment]
Accidentally found this question.

Have in mind that hiredis gem doesn't support SSL atm. Development not going as fast as I would like it to... (check pullrequests)

It can cause some issues. For example - heroku redis (v.6) addon (SSL enabled and can't be turned off by single click) will not work with hiredis lib. You will have to downgrade it to redis v.5)

So be careful with hiredis as dependency for you apps.

**Comment by eoinkelly** [comment]
@p1p1tt0 Thank you very much for sharing your experience here. Those issues are enough of a barrier that I don't think it's suitable as a default. Projects which they need the extra speed can add it as required.
