### ISSUE TITLE
Discussion: What default Rails do we want to skip?

### ISSUE THREAD

**Issue by mischa-s** [ackama/rails-template#18]
When setting up MDC-Harbours we used the command line flags `--no-rc --skip-turbolinks --skip-spring --skip-action-mailbox`.

What should the Readme recommend?

**Comment by eoinkelly** [comment]
I think `--no-rc` would be good in the README because it'll avoid people forgetting what defaults they have set in their `~/.railsrc`

**Comment by joshmcarthur** [comment]
Resolved by https://github.com/ackama/rails-template/commit/4adb3e741fd5eb49e1a4b7c9431a55463913c4e3
