### ISSUE TITLE
Referrer policy 

### ISSUE THREAD

**Issue by OBaddeley** [ackama/rails-template#185]
The [referrer policy](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referrer-Policy)
is being set in the meta tag https://github.com/ackama/rails-template/blob/main/app/views/layouts/application.html.erb.tt#L29  

In the browser console in Safari 13.1.2 and 14 a warning seen.

```
Failed to set referrer policy: The value 'origin-when-crossorigin' is not one of 'no-referrer', 'no-referrer-when-downgrade', 'same-origin', 'origin', 'strict-origin', 'origin-when-cross-origin', 'strict-origin-when-cross-origin' or 'unsafe-url'.
```

This could possibly be remedied by changing `<meta name="referrer" content="origin-when-crossorigin">` to
`<meta name="referrer" content="origin-when-cross-origin">`  but we may want to consider where the referrer policy is being set as well?

**Comment by eoinkelly** [comment]
Referrer-Policy docs: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referrer-Policy

I agree with @OBaddeley that we should probably set this in an initialiser. We may also want to consider a more privacy preserving default value e.g. `same-origin`
