### ISSUE TITLE
Enforce image size budgets through webpacker/automated processes

### ISSUE THREAD

**Issue by Rabid-Dan** [ackama/rails-template#188]
From the Front end leadership board https://rabidtech.atlassian.net/browse/MAX-58

Earlier in the year we discussed the idea of having automated tooling to help enforce an image size budget in an effort to keep the front end of our apps performant. Having this built into the rails template would be great, although I'm not 100% sure what the technical approach should be (@G-Rath might have some better ideas about where to start).

**Comment by eoinkelly** [comment]
Closing for now. This is mitigated by having Lighthouse perf tests working by default (which we already do)
