### ISSUE TITLE
Enforce BEM through linters

### ISSUE THREAD

**Issue by Rabid-Dan** [ackama/rails-template#189]
Issue originally raised at https://rabidtech.atlassian.net/browse/MAX-29

BEM is our preferred way of writing css but has a bit of an initial learning curve and can be easy to write in a way that subverts some of the base rules. Much like for our ruby and js code it would be great to have linting over our scss files in order to enforce a default set of rules for consistency.

**Comment by eoinkelly** [comment]
CSS styling is a larger conversation than this repo. We will address this with meetings and education.
