### ISSUE TITLE
Discussion: Should we be recommending that devs add things to .railsrc

### ISSUE THREAD

**Issue by eoinkelly** [ackama/rails-template#19]
Many/most devs forget what's in their `.railsrc`. I'm not sure the README in this repo should recommend using it because it's easy to forget what's in there.

**Comment by Rabid-Dan** [comment]
Maybe it just needs reformatting to make it look more optional? That bit is currently in the "installation" section so its more likely to look like one of the first things you'd try to do.

**Comment by joshmcarthur** [comment]
Resolved by https://github.com/ackama/rails-template/commit/cd639f4f545a97bf57b19cd4ff3b09d008b5463e
