### ISSUE TITLE
Convert exisitng sass-lint rules to style-lint.

### ISSUE THREAD

**Issue by Rabid-Dan** [ackama/rails-template#190]
Originally raised on front end leadership jira board: https://rabidtech.atlassian.net/browse/MAX-54

Original issue text:
---------------------------

Sass lint has been out of date for a while now and apparently has some security vulnerabilities (as well as depending on older versions of certain things).

We’ve previously looked as switching over to style-lint but now this task feels like it should be expedited.

OFLC https://bitbucket.org/rabidtech/oflc-self-rating-tool has a rule set which I think has been more or less our default on the few projects that use sass-lint so it’d be good to convert that over to start so we can start replacing sass-lint in the repos that have it. Then we can look at things like building it into the rails template and additional rule sets that we want to turn on or off.

---------------------------

We dont actually manage OFLC anymore so we'd need to find a different project to poach rules from. This issue may also relate to #189 because I think at one point we had a rule set which would enforce a BEM rules set.

**Comment by G-Rath** [comment]
I think this should be done by creating a stylelint config package, sister to [`eslint-config-ackama`](https://github.com/ackama/eslint-config-ackama). That repo can be pretty much copied as is and then just renamed + replace its eslint configs with ones for stylelint.

I know a few general rules that I'd like to see on are ones like `max-empty-lines` (set to 1 iirc), `no-eol-whitespace`, `no-empty-first-line`, and a few of the block ones around empty lines before/after blocks, braces, etc.

**Comment by eoinkelly** [comment]
We have already moved to stylelint so I'm closing this. @G-Rath the stylelint config package sounds like a good addition but I think it's outside the scope of this repo and I trust you can create a new issue/pr when you are ready to think about this again :sparkles:.
