### ISSUE TITLE
Implement some combination of active storage image optimisation + image resizing gems

### ISSUE THREAD

**Issue by Rabid-Dan** [ackama/rails-template#191]
Originally raised on the front end leadership jira board: https://rabidtech.atlassian.net/browse/MAX-61

The goal here would be the automate the image optimisation process for user uploaded images (e.g profile photos, admin controlled content) to avoid issues with large page loading times because someone in an admin sections chucked a 10mb banner image on a site.

This is worth exploring but could alternatively also just be a wiki doc with a process for achieving the same thing if implementation is a bit too heavy handed for the template.

**Comment by JamesYang76** [comment]
I am thinking of `Carrierwave` and `CarrierWave::MiniMagick` for   file upload and resizing image because  of ackama preference
https://github.com/ackama/wiki/wiki/Ackama-Technology-Preferences

**Comment by JamesYang76** [comment]
I think writing a wiki about this issue is worth regardless of applying rails template,

**Comment by eoinkelly** [comment]
I'm closing this because I think we don't have a good enough handle on what the solution should be to consider it being part of the template for all new apps. I agree with @JamesYang76 that researching and documenting this would be a worthwhile effort but that's out of scope for this project.
