### ISSUE TITLE
Make right configuration for rspec

### ISSUE THREAD

**Issue by JamesYang76** [ackama/rails-template#194]
- Delete controllers in spec because request specs are used instead of controller specs
- Add features folder in spec
- Add javascript_driver for Capybara
- Add DownloadHelpers because many rails projects include feature downloading files ,it would be great to have it as a part of this template including DownloadHelpers, configuration of rspec and example

**Comment by eoinkelly** [comment]
Time has passed so some of the points in this issue don't apply anymore:

* system specs are preferred over feature specs these days (they are basically the same but system specs are closer to the Rails default
* We already have a JS driver setup for Capybara
* I don't think enough files require the DownloadHelpers to warrant them being part of the default.

The question of whether we should still be encouraging controller specs is still relevant. I have created PR #293 to test this so further discussion on that point can live in that PR.

Closing with thanks @JamesYang76
