### ISSUE TITLE
Tell search engines not to index the app

### ISSUE THREAD

**Issue by JamesYang76** [ackama/rails-template#196]
Staging environments should not be indexed by Google. More details: https://developers.google.com/search/reference/robots_meta_tag

I think we should add the appropriate tag to your HTML. An example in a rails app might be:
```ruby
<% unless Rails.env.production? %>
  <meta name="robots" content="noindex" />
<% end %>
```

**Comment by Rabid-Dan** [comment]
I'm on board with this but we'd be better off doing it with an ENV variable rather than an environment check because services like Heroku dont have a distinction between `staging` and `production` envs and just consider them both the be `production`

**Comment by JamesYang76** [comment]
Yeah, I agree with your opinion. Heroku only has production. Just ENV variable is better than an environment check
