### ISSUE TITLE
Add unit test for react

### ISSUE THREAD

**Issue by JamesYang76** [ackama/rails-template#208]
We use rspec and Capybara for unit and feature tests. 
However there is no unit test for react components.
I think it would be good to add test library and an example under the react variant.

**Comment by G-Rath** [comment]
I don't know how useful unit testing would be for react components when we've got Capybara & co whose tests do test the react components as well, but def not against it and there are some nice wins to be had in unit testing surrounding things with `jest` & co (i.e utility functions that don't require the DOM).

I think this would be a good one for @mischa-s to weight-in on as he recently did work adding a test suite for react project using `react-testing-library` which seemed to be working well.

**Comment by mischa-s** [comment]
Yeah - I think it would be good to live with [testing library ](https://testing-library.com/) for a bit before using it on all projects but so far I've had a good time with it and as long as nothing goes terribly wrong while living with it I'd strongly recommend it for all our react projects moving forwards

**Comment by mischa-s** [comment]
will be closed by https://github.com/ackama/rails-template/pull/216
