### ISSUE TITLE
Consider adding https://github.com/ankane/strong_migrations to automated checks

### ISSUE THREAD

**Issue by joshmcarthur** [ackama/rails-template#214]
[strong_migrations](https://github.com/ankane/strong_migrations) runs checks on pending migrations to check that they are safe to run. 'Safe' in this context means that they should not unexpectedly block table reads or writes, or potentially lose data. 

This is probably a good idea for us to add to our automated checks - understanding the impact of migrations often requires some knowledge of both the underlying SQL statements _and_ the drawbacks/capabilities of the RDMS in use. This check would help less experienced developers understand the impact of a migration, and any potential optimisations to help the migration to run in a safer way.

**Comment by eoinkelly** [comment]
We have discussed this and decided it is not suitable for this repo. See discussion in PR #281

**Comment by eoinkelly** [comment]
I'm re-opening this because

1. We actually have hit some issues on mature projects having migrations added which didn't sufficiently consider the performance issues
2. We have lived with this for months on an inherited project and it hasn't been painful to deal with.

**Comment by robramsaynz** [comment]
Having a checking tool is a good idea, but is there a way to disable this in the cases that we might actually need to?

Skimming the docs seems to indicate you can disable entire checks, but it doesn't talk about how to disable checks for a specific migration a la `# rubocop:disable Metrics/AbcSize`.

**Comment by eoinkelly** [comment]
@robramsaynz yes you can wrap your code in a "I promise this is safe" block. We just need to be careful that we don't just default to doing that and not thinking about it 😄
