### ISSUE TITLE
Sentry supports sending error reports asynchrously, something we should probably enable

### ISSUE THREAD

**Issue by joshmcarthur** [ackama/rails-template#215]
async

When an error or message occurs, the notification is immediately sent to Sentry, synchronously. This means that returning a response to a user may be delayed.

We recommend creating a background job, using your background job processor, that will send Sentry notifications. The client will pass a JSON-compatible Hash representation of the Event into the callback.

``` ruby
config.async = lambda do |event, hint|
  SentryJob.perform_later(event, hint)
end
```

Or if you also use sentry-rails, you can directly use the job we defined for you:

``` ruby
config.async = lambda do |event, hint|
  Sentry::SendEventJob.perform_later(event, hint)
end
```

If the async callback raises an exception, Sentry will attempt to send synchronously.

**Comment by eoinkelly** [comment]
I think `sentry-ruby` has built-in async these days so this isn't required - see 

> By default, sentry-ruby sends events asynchronously with its own background worker.
> https://docs.sentry.io/platforms/ruby/configuration/options/#optional-settings

**Comment by eoinkelly** [comment]
@joshmcarthur I'm confident this doesn't apply anymore so am closing.
