### ISSUE TITLE
Set SameSite=lax for session cookie

### ISSUE THREAD

**Issue by stefan-squareweave** [ackama/rails-template#222]
Without having actually tested it, I believe that the session cookie is not getting a SameSite option set since this [isn't sent by Rails by default](https://github.com/rails/rails/pull/28297#issuecomment-600569507).

This apparently can cause problems with old Safari browsers, but has the benefit of providing [another layer of protection against CSRF attacks](https://portswigger.net/web-security/csrf/samesite-cookies) aside from the nonce and also more exotic [SPECTRE based attacks](https://w3c.github.io/webappsec-post-spectre-webdev/).

**Comment by eoinkelly** [comment]
I like this in theory. Have we used this on any client projects yet? Did we hit any bumps? I think this is a change that a dev team should take on during a single project first before we roll it out as a default.

**Comment by stefan-squareweave** [comment]
I've subsequently found out this is the default on newer Chrome and Firefox versions:

https://www.chromestatus.com/feature/5088147346030592
https://bugzilla.mozilla.org/show_bug.cgi?id=1604212

So I'm going to close this ticket since it's basically applied now anyway.

FYI Django since 2.1 has included Lax in the cookie by default: https://docs.djangoproject.com/en/2.2/ref/settings/#csrf-cookie-samesite . So all our python projects have it.

**Comment by eoinkelly** [comment]
@stefan-squareweave  I just noticed that Rails 6.1 has added
```
# Specify cookies SameSite protection level: either :none, :lax, or :strict.
#
# This change is not backwards compatible with earlier Rails versions.
# It's best enabled when your entire app is migrated and stable on 6.1.
# Rails.application.config.action_dispatch.cookies_same_site_protection = :lax
```
as a framework default.
