### ISSUE TITLE
Supply security.txt via middleware with yearly expiration date

### ISSUE THREAD

**Issue by G-Rath** [ackama/rails-template#223]
While we've got `.well-known/security.txt` (via #67), it's currently missing the `Expires` field which is required by the standard.

Because this ia date, we should probably move to serve the file via a middleware to handle automatically populating the field with some date in the future in the same way we do for copyright years.

**Comment by eoinkelly** [comment]
Given that it's designed to be consumed by humans I'm thinking that making this "programmatic" might be adding more complexity that is warranted just to exactly comply with the standard?

**Comment by G-Rath** [comment]
I'm not too fussed - the spec recommends it be under a year but it's not a requirement

**Comment by eoinkelly** [comment]
@G-Rath I'm going to close this because I think the outcome isn't worth the effort and keeping the year updated would either be a manual job or be just other task for CodeCare. Feel free to re-open if you feel strongly about it.
