### ISSUE TITLE
Make running template from script with input text more brittle

### ISSUE THREAD

**Issue by G-Rath** [ackama/rails-template#232]
Usually we want things to be less brittle, but in this case not brittle enough: if a template generation run throws up an unexpected input, our `template-test/ci-run` script just blindly answers with the next "answer" in its string of inputs and continues on.

This makes it super easy to have "off by one" type errors that don't actually cause errors, and thus don't fail CI.

An extreme example of this was when we landed the `react` variant but didn't update the tests - this went unnoticed for about 4 months, during which *all* of our CI tests were "off by one", as they didn't account for the new variant asking "Do you want to install React?" (so actually iirc we did technically test the `react` variant, but the last variant would always get skipped).

This also is an issue when developing, as you can easily miss dynamic prompts relating to the overriding of files:

```
Copying babel.config.js to app root directory
    conflict  babel.config.js
Overwrite /c/Users/G-Rath/workspace/projects-ackama/rails-template/template-test/dummy/react-ts-2-test-app/babel.config.js? (enter "h" for help) [Ynaqdhm] Yes
```

This is really hard to spot because of the large amount of output the generation process produces, which buries this prompts in a mountain of other logs.

Ideally I would like a setup where we can somehow tell the generator runner which questions we're expecting, and any unexpected questions would result in an error being thrown.

**Comment by G-Rath** [comment]
I think #137 could be a step in the right direction, but if I understand it correctly while it has the expected questions in it's config arrays, they're just there for easy reference and are not checked.

**Comment by G-Rath** [comment]
Current hacky way of doing it:

```
unbuffer template-test/ci-run.sh | tee >(sed "s/\x1b[^m]*m//g" > output.log);
# grep output.log for bad strings
```

**Comment by eoinkelly** [comment]
@G-Rath I think we might have solved this by moving to the YAML config. Can this be closed?
