### ISSUE TITLE
Tweak rubocop settings

### ISSUE THREAD

**Issue by eoinkelly** [ackama/rails-template#244]
After discussion with @joshmcarthur, @mischa-s and myself, we think that we should tweak rubocop settings:

* Set maximum ABC size to 18
* Set max method length to 20

These tweaks represent a sweet spot of flagging when there is really an issue without putting too much pressure on to split methods in situations where there may be no good abstractions available.

**Comment by G-Rath** [comment]
(@eoinkelly I think it'd be good if you included what the current values are, to save people having to check if this is a increase or decrease in allowance for these rules)

**Comment by joshmcarthur** [comment]
@G-Rath I believe the current values at 15 for AbcSize, and 12 for method length

**Comment by G-Rath** [comment]
@joshmcarthur cheers - in that case I definitely support these changes 👍

**Comment by eoinkelly** [comment]
Closed by #294
