### ISSUE TITLE
i18n for Javascript / React

### ISSUE THREAD

**Issue by mischa-s** [ackama/rails-template#251]
Something which has been raised a few times now when using React has been the frustration of not having access to the rails i18n translations.

On the Harbours project we used https://www.npmjs.com/package/i18n-js, and it was a pretty good experience and "just worked", so I think when we are adding React to projects we should have an option for this, or potentially just add it by default.

The benefit of adding this by default is we use (or should use) i18n for just about every project. and it is a pretty small library. The downside is that for projects which for whatever reason aren't using i18n, it will increase the size of their JS needlessly unless the team members think to audit their `package.json` remove it.

Open to other suggestions as well, this is just to get that conversation started

**Comment by mischa-s** [comment]
[il8n-js was used on ODI as well](https://github.com/ackama/odi-slpi-booking-tool/pull/82/commits/bc125bb4cfb7527754566d2e07e796b1a2db9be7). This highlighted two things:
1. Because the translations get bundled, it is important to limit what is included to just the ones being used https://github.com/ackama/odi-slpi-booking-tool/pull/87/files
2. The requirement to use the `rails-erb-loader` package to load the translations

**Comment by robotdana** [comment]
another possible way to limit to the translations used, is to always use one standard way of interacting with the translations (e.g. `I18n.t('full.path.only', { maybe: options })` or something else greppable) and have some kind of build script read the js files to find and add the specific list of translation keys actually used to the i18njs yaml file

it'd be maybe overkill if you're doing it once, but if it's something that's often needed it could be fairly straightforward to generalize

**Comment by eoinkelly** [comment]
Discussion outcome:

* We decided that this should be a wiki page
