### ISSUE TITLE
Include a .slugignore

### ISSUE THREAD

**Issue by G-Rath** [ackama/rails-template#252]
[TIL that you can have Heroku ignore stuff using `.slugignore`](https://devcenter.heroku.com/articles/slug-compiler#ignoring-files-with-slugignore), to help keep your slug size down.

Sadly the `.slugignore` is applied *before* compiling anything, so we can't ignore things like our src assets (which'd save some good space) or files from libraries like `node_modules`, but we can ignore test files like `spec/` which saves a little space (e.g. in one project it's 3.5mb), and documentation files (really we can ignore `**/*.md`).

**Comment by eoinkelly** [comment]
So `.slugignore` is for things we want in git but don't need in the deployed slug.

I did a quick survey of some of our apps and came up with:

```bash
spec/
# Factories are sometimes used for seeding etc.
!spec/factories
doc/
```

Looking at this, I'm not less convinced this is worth having as a default for our apps. The win seems _very_ marginal

**Comment by eoinkelly** [comment]
@G-Rath I'm going to close this because I think it's a bit too niche for the default template and it hasn't been a problem on any app I'm aware of. Happy to discuss again if you feel strongly about the idea.
