### ISSUE TITLE
Replace Foundation with Bootstrap

### ISSUE THREAD

**Issue by mischa-s** [ackama/rails-template#272]
Bootstrap is now the default style library used on projects and we should include that as the frontend variant instead foundation

**Comment by eoinkelly** [comment]
@mischa-s I think this might be done now eh? We have removed Foundation and added  Bootstrap as an optionl variant

**Comment by mischa-s** [comment]
> @mischa-s I think this might be done now eh? We have removed Foundation and added  Bootstrap as an optionl variant

Yup!
