### ISSUE TITLE
Turbo / Stimulus example of modal

### ISSUE THREAD

**Issue by mischa-s** [ackama/rails-template#273]

**Comment by eoinkelly** [comment]
Just noting that we don't currently install `turbo-rails`. That might change after #292

**Comment by eoinkelly** [comment]
We have a stimulus variant now which is probably where this example should live.

**Comment by eoinkelly** [comment]
Just noting that https://www.stimulus-components.com/docs does not seem to have an example modal (as of today anyway)

**Comment by eoinkelly** [comment]
Discussion outcome:

We aren't ready to add this example to this repo. We will continue iterating on modals in client apps and may re-open this if a mature pattern emerges.
