### ISSUE TITLE
Create Preact variant

### ISSUE THREAD

**Issue by mischa-s** [ackama/rails-template#274]
For most the applications that get built using this template, Preact would be more performant option than React. We should therefore look at either replacing the React variant with Preact or at least have a Preact variant

**Comment by G-Rath** [comment]
I'm hoping #307 will make this easier, though I'd also be interested in seeing some actual real world comparisons with some of our existing apps showing how much of a difference it makes.

**Comment by eoinkelly** [comment]
fwiw I think it's too early to consider making a variant for Preact. 

React (for better or worse) is the defacto choice and has the weight of a large community behind it - lots of available training, guides, SO answers etc. I understand that Preact is _almost_ React but it's not [exactly the same](https://preactjs.com/guide/v8/differences-to-react/). I think we would really need to be able to show significant wins vs React for it to become a default choice and make all our present and future Rails devs keep up with the potentially diverging evolutions of both projects.

**Comment by eoinkelly** [comment]
Discussion outcome:

* We are not ready to introduce Preact as a _default_ for our apps. We will continue to experiment with it on apps.
