### ISSUE TITLE
Include a sample image to ensure that images handled by webpack are working

### ISSUE THREAD

**Issue by G-Rath** [ackama/rails-template#308]
The `frontend-base` variant adds a commented out example of how to use the `image_pack_tag` to use images that are meant to be handled by webpack:

```
body_open_tag_with_img_example = <<~EO_IMG_EXAMPLE
  <body>
      <%
        # An example of how to load an image via Webpacker. This image is in
        # app/frontend/images/example.png
      %>
      <%# image_pack_tag "example.png", alt: "Example Image" %>
EO_IMG_EXAMPLE
gsub_file "app/views/layouts/application.html.erb", "<body>", body_open_tag_with_img_example, force: true
``` 

While working on #307 I decided to try this to confirm that things were still working and found that the example is actually just completely busted regardless of if we're using `webpacker` or `shakapacker`.

I think in general it's a good idea to have this as an actual working example with a sample image

<details>
<summary>this is the sample image I was using</summary>

![ruby-logo](https://user-images.githubusercontent.com/3151613/177020233-ec5cad9a-a2ef-43b0-92db-30cf543f055a.png)
</details>

**Comment by eoinkelly** [comment]
Closed by #324
