### ISSUE TITLE
Feature: Devise variant

### ISSUE THREAD

**Issue by joshmcarthur** [ackama/rails-template#31]
As a developer

I want to set up Devise with the standard configuration (user w. email/password auth, password resets)

So that I can quickly get going:

- [ ] Add `devise` gem
- [ ] `bundle exec rails g devise:install`
- [ ] Do we have an email address from ENV to send mail from? 00
- [ ] `bundle exec rails g devise User`
- [ ] System tests

**Comment by eoinkelly** [comment]
I think the real value in this is the system tests :sparkles:

**Comment by eoinkelly** [comment]
Maybe it should be in a separate variant but I think having a 2FA solution ready to go would be really useful. Making 2fa cheap to offer to clients has lots of security and privacy wins for them.

**Comment by eoinkelly** [comment]
Done! :sparkles:
