### ISSUE TITLE
Feature: Configurable basic auth

### ISSUE THREAD

**Issue by joshmcarthur** [ackama/rails-template#32]
As a developer

When I set up a new project

I want to be able to configure environment variables to enable HTTP auth

So that I can deploy to UAT/staging and keep things under wraps

- [x] Copy authentication code from another Ackama project
- [x] Add example environment variables, commented out

**Comment by joshmcarthur** [comment]
https://github.com/ackama/rails-template/pull/35

**Comment by eoinkelly** [comment]
I wonder whether it would be best to default to having HTTP basic auth turned **on** for all uat/staging/prod envs? It seems bit safer. What do y'all reckon?

**Comment by joshmcarthur** [comment]
@eoinkelly do you have some ideas about how we might do that? I've intentionally structured the code in #35 to always apply if there is a basic auth username and password present, so without those I'm unsure how we'd have the auth on by default.

I'm keen to avoid a Rails.env check to determine whether basic auth is enabled or not, since I've found it useful to be able to toggle off and on just with environment variables.

**Comment by eoinkelly** [comment]
Could we prompt the user for a username and password as part of the template setup?

**Comment by eoinkelly** [comment]
Actually looking at PR #35 I think it will be enabled by default in all envs because `example.env.tt` gets put in `example.env` and then that gets copied into `.env`

**Comment by eoinkelly** [comment]
Actually looking at PR #35 I think that what you have is good.

**Comment by joshmcarthur** [comment]
Closed by https://github.com/ackama/rails-template/commit/0661daf4a8061eac507a9a62a45d2353ff374c68
