### ISSUE TITLE
react-typescript variant failing in CI

### ISSUE THREAD

**Issue by eoinkelly** [ackama/rails-template#323]
See [this re-build of CI on main which used to pass](https://github.com/ackama/rails-template/runs/7661323656?check_suite_focus=true)

The relevant output is:

```
yarn run v1.22.18
$ tsc -p . --noEmit
node_modules/@types/yargs/index.d.ts:28:10 - error TS2305: Module '"yargs-parser"' has no exported member 'DetailedArguments'.

28 import { DetailedArguments, Configuration } from 'yargs-parser';
            ~~~~~~~~~~~~~~~~~

node_modules/@types/yargs/index.d.ts:28:29 - error TS2305: Module '"yargs-parser"' has no exported member 'Configuration'.

28 import { DetailedArguments, Configuration } from 'yargs-parser';
                               ~~~~~~~~~~~~~


Found 2 errors in the same file, starting at: node_modules/@types/yargs/index.d.ts:28

error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

This issue seems to be strongly correlated to https://github.com/electron-userland/electron-builder/issues/5446#issuecomment-749284512

**Comment by G-Rath** [comment]
https://github.com/yargs/yargs-parser/issues/452 is the issue to follow

**Comment by eoinkelly** [comment]
https://github.com/yargs/yargs-parser/pull/455 has resolved this now.

**Comment by G-Rath** [comment]
Yeah but the TS variant still seems to be failing for some reason - I'm looking into this
