### ISSUE TITLE
Our rack-canonical-host setup breaks on render.com

### ISSUE THREAD

**Issue by eoinkelly** [ackama/rails-template#328]
I played with deploying an app generated by this template on https://render.com and hit a confusing issue with our rack-canonical-host setup

We use [rack-canonical-host](https://github.com/tylerhunt/rack-canonical-host) with the `HOSTNAME` env var. Render sets `HOSTNAME` but doesn't set it to a fully qualified domain e.g. it sets it to something like `HOSTNAME=srv-cbm836fho1kta1m6cu6g-5fb64bb76c-qvsd5`. This means our setup in `config.ru` breaks out of the box because we try to HTTP 301 to `https://srv-cbm836fho1kta1m6cu6g-5fb64bb76c-qvsd5/`. This also doesn't generate any logging output so is quite confusing to debug.

The fix here would be to either change the name of the env var we use e.g. the `rack-canonical-host` suggests `CANONICAL_HOST` or to add an exception for render.com. Render always sets the `RENDER` env var which we can use for this. 

Is there a particular reason we use `HOSTNAME` as the env var? Is there any reason we can't change it to something less likely to conflict like `CANONICAL_HOST` or even `RAILS_CANONICAL_HOST`?

**Comment by G-Rath** [comment]
I'm +1 on `CANONICAL_HOST` - I don't mind `RAILS_CANONICAL_HOST` but think this is something we should be able to standardize across our stacks for which `CANONICAL_HOST` would be more agnostic.

**Comment by eoinkelly** [comment]
@G-Rath That makes sense. `CANONICAL_HOST` should be safe enough I think and matches the recommendation in the `rack-canonical-host` [README])https://github.com/tylerhunt/rack-canonical-host#environment-specific-configuration)
