### ISSUE TITLE
Feature: Sidekiq variant

### ISSUE THREAD

**Issue by joshmcarthur** [ackama/rails-template#33]
As a developer

I want to _optionally_ introduce a dependency on Sidekiq (Redis, additional process)

So that I only get Sidekiq if I actually need it

- [x] Move existing Sidekiq generation code to a variant
- [ ] Add check for Redis to bin/setup (?)
- [ ] Add new variant tests

**Comment by eoinkelly** [comment]
Note for whoever picks this up: currently sidekiq is baked in by default and has both an initializer and a section in `routes.rb`

**Comment by joshmcarthur** [comment]
https://github.com/ackama/rails-template/pull/48

**Comment by eoinkelly** [comment]
@joshmcarthur this is done eh?

**Comment by Rabid-Dan** [comment]
This has been implemented now so closing this particular ticket. #113 is still open for iteration so should be worked on separately as the next bit in the chain.
