### ISSUE TITLE
Create a variant for each kind of deployed environment

### ISSUE THREAD

**Issue by eoinkelly** [ackama/rails-template#331]
I think it could be good to have a variants for each of

1. Capistrano deployed apps
2. Heroku deployed apps 
3. ??? maybe others?

In particular, it is annoying to have to install and setup the basics of Capistrano when we need it but I think most kinds of envs have their own specific files we could add.

**Comment by G-Rath** [comment]
Idk if we need anything special for Heroku envs? I think having one for Capistrano would be good, though I'm really wanting to extract our aws helper into an actual gem (especially now that I've got SSM port forwarding working) whichd make that variant smaller.

I've pretty much got the output in a repo which I use for developing our infrastructure modules repo - you could probably copy and paste things from that directly.

**Comment by eoinkelly** [comment]
We have discussed this and think that, for now, having the following variants would be useful:

1. Generic Capistrano
2. Ackama EC2 specific Capistrano

PR #335 is addressing these.
