### ISSUE TITLE
Discussion: Remove Bootstrap variant

### ISSUE THREAD

**Issue by mischa-s** [ackama/rails-template#34]
Currently the template has a bootstrap variant but does not provide options to use it. In conversation with @eoinkelly it came up that Ackama almost never uses Bootstrap any more, so rather than fixing this, the suggestion is to remove the template. Thoughts and feelings welcome...

**Comment by joshmcarthur** [comment]
Just an FYI, while we can remove it, it will consistently conflict when we move changes in from the upstream, since this is where it originates.

**Comment by Rabid-Dan** [comment]
I'm open to opinions but I think for our current usage it makes sense to remove it. In our css standards meeting I remember coming to the conclusion that foundation was our default for rails projects but we might want to see if we can move further away from frameworks all together in the future so having bootstrap as an option doesn't really seem necessary

**Comment by G-Rath** [comment]
> while we can remove it, it will consistently conflict when we move changes in from the upstream

I think this is a good reason to keep it.

> the template has a bootstrap variant but does not provide options to use it.
> so rather than fixing this, the suggestion is to remove the template

@mischa-s is the only work required for "fixing" this to add support for selecting it as a option, or do we have to perform maintenance work on it?

I think if there is almost never any work needing to be on it (maintenance or otherwise), than it might be "nice to have" to support selecting it as an option, but otherwise sounds like removing it will just add to our maintenance burden w/o any upside.

**Comment by eoinkelly** [comment]
Will we ever want to pull changes in from upstream? My thought is that we have basically forked at this point

**Comment by G-Rath** [comment]
> Will we ever want to pull changes in from upstream? My thought is that we have basically forked at this point

That sounds like the highest priority discussion: Should we pull the trigger and officially hard fork? (i.e break the upstream connection).

**Comment by eoinkelly** [comment]
@G-Rath I support doing that

**Comment by joshmcarthur** [comment]
It's worth doing, since this fork is off my fork, and I _do_ merge upstream changes into my fork (I especially do this around major Rails version updates since I'm not necessarily on top of tooling and API changes around that)

**Comment by eoinkelly** [comment]
Are we ok if I close this issue in favour of #129 ? #129 links to this issue so the discussion will be available.

**Comment by Rabid-Dan** [comment]
Resolved by #132 and reflected on #129 closing this now.
