### ISSUE TITLE
Discuss having a default way to log security events

### ISSUE THREAD

**Issue by eoinkelly** [ackama/rails-template#340]
We want a conventional way to log significant security events e.g. user sign-in attempt 

We have implemented this idea on multiple apps but in slightly different ways. It seems like something where we could find a sensible default.

**Comment by eoinkelly** [comment]
Our solution here looks quite different depending on whether we want to store these audit logs in the DB or as actual logs files. I have implemented the log file version a few times on different projects. 

The key benefit of log files is that they can be quickly shipped off the box into an immutable long-term storage like CloudWatch which means historical logs won't automatically be suspicious if the Rails app was compromised. 

The downside of log files is that you have to implement your own way of searching them. This can be mitigated by logging as JSON - then services like CloudWatch, Loggly etc. can give you structured searching out of the box

Most of the [gems available for audit logging](https://hybrd.co/posts/audit-logging-in-rails) log to the DB. 

I personally think we want to log to a file.

**Comment by G-Rath** [comment]
I'm +1 on sending them to a file - I think that's also more robust from an availability POV: log storage is usually much easier and cheaper at scale.
