### ISSUE TITLE
Enable branch coverage in SimpleCov

### ISSUE THREAD

**Issue by G-Rath** [ackama/rails-template#343]
Currently we're only measuring line coverage, which means one line conditionals like guards are always considered covered even though these often have important behaviour that we should make sure we cover. This also doesn't combine well with our rubocop rules which require us to use one-line guards when possible, which results in "hiding" code from coverage.

https://github.com/simplecov-ruby/simplecov#branch-coverage-ruby--25

**Comment by eoinkelly** [comment]
How big an impact will this have on a team hitting a particular coverage percentage. I :100: agree this is a good idea but we should do some comms with teams beforehand if merging this means hitting 95% will be a lot more work.
