### ISSUE TITLE
Potential addition: Run assets:precompile with lower CPU priority during capistrano deploys

### ISSUE THREAD

**Issue by eoinkelly** [ackama/rails-template#357]
I added this to a client project to fix an issue where response times would go up during deploys because webpack ate all the CPU. It appears to work well enough that I think we could discuss whether it is something we want in this template. Perhaps commented out or perhaps as a default?

```ruby
# config/deploy.rb

###
# The capistrano-rails gem provides a `deploy:assets:precompile` task. We
# override that task here because we want to run `bundle exec rails assets:precompile`
# with a lower CPU priority than other processes on the system so that it
# doesn't take CPU away from the running puma processes.
#
# We use the unix `nice` command to achieve this ("man nice" for help). Nice's
# process priorities range from -19 (highest priority) to +20 (lowest priority).
# Processes on Ubuntu have a "nice value" of 0 by default so we choose a
# priority of "3" which is slightly lower than other processes.
#
Rake::Task["deploy:assets:precompile"].clear_actions
namespace :deploy do
  namespace :assets do
    task :precompile do
      on release_roles(fetch(:assets_roles)) do
        within release_path do
          with rails_env: fetch(:rails_env), rails_groups: fetch(:rails_assets_groups) do
            execute "nice", "-n", "3", "bundle", "exec", "rails", "assets:precompile"
          end
        end
      end
    end
  end
end

```

**Comment by G-Rath** [comment]
I'm 👍 on doing it by default - if its stable and doesn't hugely impact the overall compile time, might as well do it 🤷 

As discussed privately, we're both a bit ick on this but so long as it remains "write once" I think we can draw the line of how much Unix-ish-only stuff we've got going on as just after this.

**Comment by eoinkelly** [comment]
I submitted this to capistrano-rails on the off-chance they are keen https://github.com/capistrano/rails/issues/258

**Comment by eoinkelly** [comment]
An update on this after living with it for a while: 

This technically works every time but it's not always effective. We have still noticed some issues serving traffic on small (t3.medium) EC2 instances while Webpack is compiling.

We have been successful using `cpulimit` rather than `nice` but we had to compile it ourselves from https://github.com/opsengine/cpulimit to get the version which also limits child processes. 

I am now doubtful that this is something we want in this template because it's use is very specific but I'll leave this issue open for a while so we can discuss it.

**Comment by eoinkelly** [comment]
I'm closing this because it's quite niche and requires a very specific setup on the server to work so is not suitable for this template
