### ISSUE TITLE
Remove test/ directory as we (currently) use rspec instead

### ISSUE THREAD

**Issue by eoinkelly** [ackama/rails-template#38]
Merrin mentioned that we create `test/` and `spec/` in the Rails app which is bit confusing. 

I did some research by creating a bunch of rails apps

```bash
rails --version
Rails 6.0.1

# create rails apps to compare
rails new --no-rc eoin-defaults
rails new --no-rc --skip-test  eoin-skip-test
rails new --no-rc  --skip-system-test eoin-skip-system-test
rails new --no-rc --skip-test --skip-system-test eoin-skip-test-skip-system-test
```

I found that if you pass `--skip-test --skip-system-test` then:

* the `:test` group in Gemfile is not created
* the `test/` directory is not created

In all other cases the `test/` directory is created.

### Conclusion

I think we want the `:test` group to be created in `Gemfile` so we should manually remove the `test/` dir as part of our template (in the `after_bundle` hook so we run after the built-in Rails new stuff has already run).

**Comment by joshmcarthur** [comment]
Implemented in https://github.com/ackama/rails-template/pull/39
