### ISSUE TITLE
Automatically fetch latest version of Ackama template README

### ISSUE THREAD

**Issue by joshmcarthur** [ackama/rails-template#41]
As a developer creating a new Rails project

I want to get a project created with all the latest documentation recommendations from the wider Ackama dev team

So that I don't have to think about document content or style.

- [ ] Decide where README template should canonically live (it's in the wiki at the moment, which is private)
- [ ] Determine how to fetch it (e.g. private wiki might need to be cloned, public could `curl` it)
- [ ] Add step to template.rb to fetch the README _somehow_

**Comment by eoinkelly** [comment]
I think we should move README template into our dotfiles repo and make that public (and maybe also rename it to `ackama-templates` or something because it's more than files which begin with `.`

**Comment by eoinkelly** [comment]
FYI we have some sections in the generated README which do not come from the Ackama README template e.g. the section about running in production locally

**Comment by eoinkelly** [comment]
It's not clear how to proceed here yet. We have made a first step by moving the Rails README template to https://github.com/ackama/doc-templates but we need some discussion there to see whether we end up with a _rails specific_ README there or a more generic README that can be applied to other projects.

**Comment by eoinkelly** [comment]
Closing because we don't think taking action on this is realistic in near future.
