### ISSUE TITLE
GitHub CI workflow should run Jest tests

### ISSUE THREAD

**Issue by G-Rath** [ackama/rails-template#422]
Alternative title: Ensure that Jest is being set-up correctly for all possible variant combos

The practical problem we want to solve here is "the GHA workflow generated by this template does not run Jest tests", but really I think this is the same issue as #408 but for Jest, where we included Jest / `testing-library` originally with our React variant as that was the only one with enough complexity & dedicated JS to be worth having dedicated tests; however we've now started using Stimulus which can (and is) also testable with Jest / `testing-library`.

Overall I think it probably makes sense to do a similar solution as with #421 where we land a new `frontend-base-jest` variant and have dedicated `jest` sub-variants for specific frontend variant like we do with TypeScript.

**Comment by G-Rath** [comment]
Related: turns out we're not installing `@types/jest` which is a bit odd but even odder is we're not apparently hit any problems with that on our projects which is why we've not noticed.

I'm not completely surprised because 1. another dependency might be pulling it in and 2. Jest has been working to improve their shipped types which could be good enough now that we've not run into problems; but still worth looking a bit deeper into.

**Comment by robotdana** [comment]
my assumption would be this goes in the js checks section
