### ISSUE TITLE
Support Google Tag Manager out of the box

### ISSUE THREAD

**Issue by G-Rath** [ackama/rails-template#439]
We tend to have to setup at least Google Tag Manager on most of our apps, and while the snippiet is always the same we usually do it slightly differently each time - sometimes we just have it in `layouts/application.html.erb`, sometimes its in `layouts/_google.html.erb`, and so on.

It would be good if we could have an established pattern for structuring analytics in views, and had support out of the box for enabling Google Tag Manager by just setting an env variable.

We could also hopefully use this to help encourage good practices around analytics.

**Comment by robotdana** [comment]
pull from an existing app

**Comment by eoinkelly** [comment]
Given that analytics are sometimes a contentious topic, I'm hesitant to make it part of *every* app. I think we should make this a variant that devs opt-in to via the YAML config. That would make the path clear for templating other kinds of analytics too.

**Comment by robotdana** [comment]
csp needs to be updated to allow google tag manager and its children

**Comment by robotdana** [comment]
we should keep that as locked down as possible
