### ISSUE TITLE
Consider removing Rubocop's `TargetRubyVersion` config customisation

### ISSUE THREAD

**Issue by eoinkelly** [ackama/rails-template#448]
Currently we lock rubocop's `TargetRubyVersion` to the oldest version of Ruby that the latest version of Rails supports (`2.7` as of Rails 7.0).

The [Rubocop docs for TargetRubyVersion](https://docs.rubocop.org/rubocop/configuration.html#setting-the-target-ruby-version) describe it as 
> Users may let RuboCop know the oldest version of Ruby which your project supports

In the absence of `TargetRubyVersion` then Rubocop targets whichever version of Ruby is running this template as part of `rails new`. 

I find it hard to imagine a team which runs the same Rails app on different versions of Ruby in their local dev environments so it doesn't seem necessary to tell Rubocop that it needs to support versions of Ruby older than the version being used for `rails new` by the dev who runs this template.

I think we should remove this setting and assume that the developer who is running `rails new` has already made a deliberate choice about which Ruby version they are using.

**Comment by G-Rath** [comment]
I'm not wholly against this, but I'm not sure if you're correctly underlying the impact of it - our template generates a Rails application that _doesn't_ have `TargetRubyVersion`, meaning that `rubocop` will use the version of Ruby that is currently being used by the developer (which should be the version specified in `.ruby-version`).

However, that does not mean the developer generating the application is using a particular version of Ruby - so by having `TargetRubyVersion` for the templates `rubocop` we're (in theory) ensuring the template can be used with a range of Ruby versions, which is a nice thing to do given this is an open-source repository as other people wanting to use this template might for some reason want to use a non-latest version of Ruby.

**Comment by eoinkelly** [comment]
Thank you for that @G-Rath - turns out my thinking wasn't clear on this. I agree with your assessment so will close this.
