### ISSUE TITLE
Move from SASS `@import` to `@use`

### ISSUE THREAD

**Issue by lukeify** [ackama/rails-template#488]
[`@import`](https://sass-lang.com/documentation/at-rules/import/) is deprecated, while [`@use`](https://sass-lang.com/documentation/at-rules/use/) is sparkly and has a number of benefits outlined on the sasslang page just linked, namely reducing the number of globally scoped members in favour of namespacing. 

It should be a drop-in replacement for `@import` in the simple case where partials are concatenated together into an output.

**Comment by eoinkelly** [comment]
I agree we should move as much as possible to `@use`. FYI We can't do it for our bootstrap variant because Bootstrap [won't support @use until v6 (v5 is current)](https://github.com/twbs/bootstrap/issues/30025#issuecomment-574825600)
