### ISSUE TITLE
Use `always` for `SelfClosingTag` in erb-lint

### ISSUE THREAD

**Issue by G-Rath** [ackama/rails-template#509]
The default for this rule is `never` which is arguably the better setting since we've never needed to support XHTML and results in slightly smaller HTML, but Prettier enforces the opposite and is not configurable - in this case I think it would be better if we're consistent across our stacks vs the very tiny win of slightly less code.

https://github.com/Shopify/erb-lint?tab=readme-ov-file#selfclosingtag

**Comment by lukeify** [comment]
Discussed at Rails Guild on 3 November 2023, this seems good and is ready for dev.

**Comment by G-Rath** [comment]
I realised that also JSX requires the closing `/` which is something we're more likely to be writing in our React apps vs native HTML
