### ISSUE TITLE
Devise: Minimum password length should be set to 16 characters

### ISSUE THREAD

**Issue by joshmcarthur** [ackama/rails-template#87]
NZISM:

> System Classification(s): All Classifications; Compliance: SHOULD [CID:1858]
Agencies SHOULD implement a password policy enforcing either:
>
> a minimum password length of 16 characters with no complexity requirement; or
> a minimum password length of ten characters, consisting of at least three of the following character sets:
> lowercase characters (a-z);
> uppercase characters (A-Z);
> digits (0-9); and
> punctuation and special characters.

I recommend we increase our required password length to 16 chars.

**Comment by eoinkelly** [comment]
![Screenshot 2020-05-27 13 47 42](https://user-images.githubusercontent.com/599867/82968182-d0298100-a020-11ea-9fb9-3dbdf16127df.png)

FYI 1Password's _Strong requirements_ is 14 chars.

**Comment by eoinkelly** [comment]
FWIW 16 seems long enough that it might be a bit user hostile in some situations but I guess it is safer to have a long default that we then drop later in consultation with the client
